### ISSUE TITLE
How its can integrate in hass.io ?

### ISSUE THREAD

**Issue by xrays72** [swim2sun/hass-config-milo#1]
@swim2sun 
Hello, thank you for your work.
Please write how its can integrate in hass.io ?

**Comment by swim2sun** [comment]
Hi @xrays72, this repo is my home assistant configuration, it's not a hass.io component.

Do you want integrate `xiaomi_fan`? If yes, the steps are like this:

> You need do this on the machine where you installed your home assistant.

1. Clone this repo (star this repo is better 😄)
2. Uninstall the `python-miio` which installed by HA.
```shell
pip uninstall python-miio
```
3. Install the `python-miio` provided by this repo
```shell
pip install libs/python_miio-0.5.3-py3-none-any.whl
```
4. Copy the `custom_components/xiaomi_miio_fan` to your `custom_components`.
```shell
cp custom_components/xiaomi_miio_fan path/to/your/custom_components
```
5. Add xiaomi_fan configuration to your `configuration.yaml`
```yaml
fan:
  - platform: xiaomi_miio_fan
    name: xiaomi_fan
    host: 192.168.xx.xx
    token: xxxxxxxxxxxxxxx
```

Good luck!
